CREATE TABLE XXJ_QRTZ_JOB_DETAILS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    JOB_CLASS_NAME   VARCHAR2(250) NOT NULL,
    IS_DURABLE VARCHAR2(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE XXJ_QRTZ_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    JOB_NAME  VARCHAR2(200) NOT NULL,
    JOB_GROUP VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(250) NULL,
    NEXT_FIRE_TIME NUMBER(13) NULL,
    PREV_FIRE_TIME NUMBER(13) NULL,
    PRIORITY INTEGER NULL,
    TRIGGER_STATE VARCHAR2(16) NOT NULL,
    TRIGGER_TYPE VARCHAR2(8) NOT NULL,
    START_TIME NUMBER(13) NOT NULL,
    END_TIME NUMBER(13) NULL,
    CALENDAR_NAME VARCHAR2(200) NULL,
    MISFIRE_INSTR NUMBER(2) NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
        REFERENCES XXJ_QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE XXJ_QRTZ_SIMPLE_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    REPEAT_COUNT NUMBER(7) NOT NULL,
    REPEAT_INTERVAL NUMBER(12) NOT NULL,
    TIMES_TRIGGERED NUMBER(10) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES XXJ_QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE XXJ_QRTZ_CRON_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    CRON_EXPRESSION VARCHAR2(200) NOT NULL,
    TIME_ZONE_ID VARCHAR2(80),
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES XXJ_QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE XXJ_QRTZ_SIMPROP_TRIGGERS
  (          
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    STR_PROP_1 VARCHAR2(512) NULL,
    STR_PROP_2 VARCHAR2(512) NULL,
    STR_PROP_3 VARCHAR2(512) NULL,
    INT_PROP_1 INTEGER NULL,
    INT_PROP_2 INTEGER NULL,
    LONG_PROP_1 NUMBER(20) NULL,
    LONG_PROP_2 NUMBER(20) NULL,
    DEC_PROP_1 NUMBER(13,4) NULL,
    DEC_PROP_2 NUMBER(13,4) NULL,
    BOOL_PROP_1 VARCHAR2(1) NULL,
    BOOL_PROP_2 VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES XXJ_QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE XXJ_QRTZ_BLOB_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES XXJ_QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE XXJ_QRTZ_CALENDARS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    CALENDAR_NAME  VARCHAR2(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);

CREATE TABLE XXJ_QRTZ_PAUSED_TRIGGER_GRPS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR2(200) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);

CREATE TABLE XXJ_QRTZ_FIRED_TRIGGERS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    ENTRY_ID VARCHAR2(95) NOT NULL,
    TRIGGER_NAME VARCHAR2(200) NOT NULL,
    TRIGGER_GROUP VARCHAR2(200) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    FIRED_TIME NUMBER(13) NOT NULL,
    SCHED_TIME NUMBER(13) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE VARCHAR2(16) NOT NULL,
    JOB_NAME VARCHAR2(200) NULL,
    JOB_GROUP VARCHAR2(200) NULL,
    IS_NONCONCURRENT VARCHAR2(1) NULL,
    REQUESTS_RECOVERY VARCHAR2(1) NULL,
    PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);

CREATE TABLE XXJ_QRTZ_SCHEDULER_STATE
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    INSTANCE_NAME VARCHAR2(200) NOT NULL,
    LAST_CHECKIN_TIME NUMBER(13) NOT NULL,
    CHECKIN_INTERVAL NUMBER(13) NOT NULL,
    PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);

CREATE TABLE XXJ_QRTZ_LOCKS
  (
    SCHED_NAME VARCHAR2(120) NOT NULL,
    LOCK_NAME  VARCHAR2(40) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);

CREATE SEQUENCE SEQ_XXJ_QRTZTRINFO INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_XXJ_QRTZTRLOG INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_XXJ_QRTZTRLOGGLUE INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_XXJ_QRTZTRREGISTRY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
CREATE SEQUENCE SEQ_XXJ_QRTZTRGROUP INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;

CREATE TABLE XXJ_QRTZ_TRIGGER_INFO (
  id NUMBER(11) DEFAULT SEQ_XXJ_QRTZTRINFO.NEXTVAL NOT NULL,
  job_group NUMBER(11) NOT NULL ,
  job_cron VARCHAR2(128) NOT NULL ,
  job_desc VARCHAR2(255) NOT NULL,
  add_time DATE DEFAULT NULL,
  update_time DATE DEFAULT NULL,
  author VARCHAR2(64) DEFAULT NULL,
  alarm_email VARCHAR2(255) DEFAULT NULL ,
  executor_route_strategy VARCHAR2(50) DEFAULT NULL,
  executor_handler VARCHAR2(255) DEFAULT NULL,
  executor_param VARCHAR2(512) DEFAULT NULL ,
  executor_block_strategy VARCHAR2(50) DEFAULT NULL ,
  executor_fail_strategy VARCHAR2(50) DEFAULT NULL ,
  glue_type VARCHAR2(50) NOT NULL ,
  glue_source CLOB DEFAULT NULL,
  glue_remark VARCHAR2(128) DEFAULT NULL ,
  glue_updatetime DATE DEFAULT NULL ,
  child_jobid VARCHAR2(255) DEFAULT NULL ,
  PRIMARY KEY (id)
);

COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.job_group IS '执行器主键ID';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.job_cron IS '任务执行CRON';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.author  IS '作者';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.alarm_email IS '报警邮件';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.executor_route_strategy IS '执行器路由策略';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.executor_handler IS '执行器任务handler';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.executor_param IS '执行器任务参数';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.executor_block_strategy IS '阻塞处理策略';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.executor_fail_strategy IS '失败处理策略';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.glue_type IS 'GLUE类型';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.glue_source IS 'GLUE源代码';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.glue_remark IS 'GLUE备注';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.glue_updatetime IS 'GLUE更新时间';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_INFO.child_jobid IS '子任务ID，多个逗号分隔';

CREATE TABLE XXJ_QRTZ_TRIGGER_LOG (
  id NUMBER(11) DEFAULT SEQ_XXJ_QRTZTRLOG.NEXTVAL NOT NULL,
  job_group NUMBER(11) NOT NULL,
  job_id NUMBER(11) NOT NULL ,
  glue_type VARCHAR2(50) DEFAULT NULL ,
  executor_address VARCHAR2(255) DEFAULT NULL ,
  executor_handler VARCHAR2(255) DEFAULT NULL ,
  executor_param VARCHAR2(512) DEFAULT NULL ,
  trigger_time DATE DEFAULT NULL ,
  trigger_code NUMBER(11) NOT NULL ,
  trigger_msg VARCHAR2(2048) DEFAULT NULL ,
  handle_time DATE DEFAULT NULL ,
  handle_code NUMBER(11) NOT NULL ,
  handle_msg VARCHAR2(2048) DEFAULT NULL ,
  PRIMARY KEY (id)
);

COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.job_group IS '执行器主键ID';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.job_id IS '任务，主键ID';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.glue_type IS 'GLUE类型';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.executor_address IS '执行器地址，本次执行的地址';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.executor_handler IS '执行器任务handler';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.executor_param IS '执行器任务参数';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.trigger_time IS '调度-时间';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.trigger_code IS '调度-结果';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.trigger_msg IS '调度-日志';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.handle_time IS '执行-时间';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.handle_code IS '执行-状态';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOG.handle_msg IS '执行-日志';

CREATE TABLE XXJ_QRTZ_TRIGGER_LOGGLUE (
  id NUMBER(11)  DEFAULT SEQ_XXJ_QRTZTRLOGGLUE.NEXTVAL NOT NULL,
  job_id NUMBER(11) NOT NULL ,
  glue_type VARCHAR2(50) DEFAULT NULL ,
  glue_source clob ,
  glue_remark VARCHAR2(128) NOT NULL ,
  add_time timestamp  DEFAULT NULL,
  update_time timestamp  DEFAULT sysdate,
  PRIMARY KEY (id)
);

COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOGGLUE.job_id IS '任务，主键ID';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOGGLUE.glue_type IS 'GLUE类型';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOGGLUE.glue_source IS 'GLUE源代码';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_LOGGLUE.glue_remark IS 'GLUE备注';

CREATE TABLE XXJ_QRTZ_TRIGGER_REGISTRY (
  id NUMBER(11) DEFAULT SEQ_XXJ_QRTZTRREGISTRY.NEXTVAL NOT NULL,
  registry_group VARCHAR2(255) NOT NULL,
  registry_key VARCHAR2(255) NOT NULL,
  registry_value VARCHAR2(255) NOT NULL,
  update_time timestamp DEFAULT sysdate NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE XXJ_QRTZ_TRIGGER_GROUP (
  id NUMBER(11) DEFAULT SEQ_XXJ_QRTZTRGROUP.NEXTVAL NOT NULL,
  app_name VARCHAR2(64) NOT NULL ,
  title VARCHAR2(12) NOT NULL ,
  "ORDER" NUMBER(4) DEFAULT 0 NOT NULL ,
  address_type NUMBER(4) DEFAULT 0 NOT NULL ,
  address_list VARCHAR2(512) DEFAULT NULL ,
  PRIMARY KEY (id)
);

COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_GROUP.app_name IS '执行器AppName';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_GROUP.title IS '执行器名称';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_GROUP."ORDER" IS '排序';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_GROUP.address_type IS '执行器地址类型：0=自动注册、1=手动录入';
COMMENT ON COLUMN XXJ_QRTZ_TRIGGER_GROUP.address_list IS '执行器地址列表，多地址逗号分隔';

INSERT INTO XXJ_QRTZ_TRIGGER_GROUP ( app_name, title, "ORDER", address_type, address_list) values ( 'xxl-job-executor-sample', '示例执行器', '1', '0', null);

